### ISSUE TITLE
Typings file not present

### ISSUE THREAD

**Issue by mdoff** [kriszyp/ordered-binary#2]
Hi!
First I would like to thank you for your contribution into open source and javascript.

I noticed that in `package.json` file there is this entry https://github.com/kriszyp/ordered-binary/blob/7fe66ed3757d037b13d5d5622089c3082bfbe419/package.json#L29 but there is no `index.d.ts` present.
Could you either remove this line either add typings?

I noticed that when VSCode intelisense went crazy and started complainig about it.

**Comment by kriszyp** [comment]
Good catch and suggestion, thank you! Should be published in v1.2.4.
