### ISSUE TITLE
The use of `instanceof Array` may return false negative result

### ISSUE THREAD

**Issue by panmenghan** [kriszyp/ordered-binary#4]
```js
const vm = require('node:vm')
const context = {}
const script = new vm.Script('arr = [1]')
vm.createContext(context)
script.runInContext(context)

console.info(context.arr) // -> [ 1 ]

context.arr instanceof Array // -> false
Array.isArray(context.arr) // -> true
```

Some references:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs_isarray
https://stackoverflow.com/a/22289982

Benchmark:
https://www.measurethat.net/Benchmarks/Show/5377/0/array-isarray-vs-instanceof#latest_results_block

**Comment by kriszyp** [comment]
Thank you for the well-researched suggestion!
I will raise a few issues here. First, it is also possible to create a derivative of an array (prototype is array), which is pretty array-like, but is not an array according `Array.isArray`:
```
let a = ['a','b'];
let a2 = Object.create(a);
Array.isArray(a2) -> false
// but really is an array in the sense of how we use it in ordered-binary:
for (let i = 0; i < a2.length;i++){ let v = a[i]; // iterates through the values of a2
a2.constructor.toString() -> also indicates array.
```
It could also be worth considering if iterables should be treated as array-like (in most cases in JS they are). And another example is `arguments` is an array in the sense that we use it ordered-binary, but `Array.isArray(arguments)`. These are all cases are where one could say Array.isArray returns "false negative" as well. The point being that array-ness is a lot more nuanced than a single simple binary answer (as `Array.isArray` can somewhat deceptively suggest), usually has more to do with how the object will be used.

Also, I double checked the performance, and unfortunately measurethat.net looks like it is not even remotely close to being accurate (off by a couple orders of magnitude!). In reality, `Array.isArray` is actually about twice as fast `instanceof Array` (and 400 times faster than what measurethat measured!), but about twice as slow as `value.constructor == Array` (this is the fastest, but probably a bit too strict).

Anyway, all that being said, I am happy to switch to `Array.isArray`, especially if you have a legitimate use case where you need to use cross-context arrays.

**Comment by panmenghan** [comment]
When I try to access the lmdb db over web console (xterm.js + websocket + repl), and encounter the problem.

[The demo repo](https://github.com/panmenghan/lmdb_array_issue)

**Comment by panmenghan** [comment]
JSON.stringify also treat the following array-like-object as not array:

```js
JSON.stringify(Object.create([])) // -> '{}'

(function(){return JSON.stringify(arguments)})() // -> '{}'
```

I checked the libs I have used before, the methods they check what is array object:

https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L11286
https://github.com/facebook/jest/blob/main/packages/jest-get-type/src/index.ts#L31
https://github.com/sindresorhus/is/blob/main/source/index.ts#L174

**Comment by kriszyp** [comment]
Ok, published the switch to Array.isArray in 1.3.0.

(And just to be clear, the reason is simply because you have a use case for it and it is faster; I do hope you understand that array-ness is _not_ a binary concept, regardless of whether some libraries use this function, and it is valuable to know when and when it is not to appropriate `Array.isArray`, which varies significantly on the situation).

**Comment by panmenghan** [comment]
I understand. Thanks for your libraries.
