### ISSUE TITLE
node.js 23 change causes RangeError on writeKey when calling utf8Write

### ISSUE THREAD

**Issue by uwx** [kriszyp/ordered-binary#6]
The call to utf8Write at:

https://github.com/kriszyp/ordered-binary/blob/348b9030871b676bde743b419b193d8697467820/index.js#L68

Causes `RangeError: "length" is outside of buffer bounds at Buffer.utf8Write (node:internal/buffer:1066:13)` due to [this range check](https://github.com/nodejs/node/commit/3800d60c661b915838aeb3b8a6c3b71625423f80#diff-ec53d27b3c64c43cc2d4773dd88046ebb149e3d89e31d838df3252c8d5de89adR1065) added in node v23.0.0.

This also causes `Error: Key size is larger than the maximum key size` when inserting to a lmdb-js database on node 23.0.0 and above.

**Comment by kriszyp** [comment]
Fixed in v1.5.3 (will publish a newer version of lmdb-js sometime with this reference as well, although it uses ^1.5.2, so should allow for this update).

**Comment by cap10morgan** [comment]
Can confirm this is fixed in v1.5.3. 🚀 Can probably close this issue.
